// Full exercise catalog for CP therapy — physiotherapy + occupational therapy.
// The `slug` matches the id used in public/neuro-bridge/app.js so the in-app
// launcher can pre-select the same exercise inside the prototype player.

export type ExerciseCategory = "pt" | "ot";
export type ExerciseTrack = "arm" | "leg" | "balance";

export type Exercise = {
  slug: string;
  name: string;
  category: ExerciseCategory;
  track: ExerciseTrack;
  icon: string;
  focus: string;
  description: string;
  benefits: string;
  gamified: boolean; // all exercises are now playable games in the prototype
};

export const EXERCISES: Exercise[] = [
  // ============ PHYSIOTHERAPY (from MVP + expanded CP set) ============
  { slug: "arm", name: "Arm Raise", category: "pt", track: "arm", icon: "🎈",
    focus: "Shoulder flexion",
    description: "Raise arms overhead to pop floating balloons.",
    benefits: "Improves shoulder ROM, upper-limb strength and posture.",
    gamified: true },
  { slug: "reach", name: "Forward Reach", category: "pt", track: "arm", icon: "🍎",
    focus: "Anterior reach",
    description: "Reach forward to touch an on-screen target apple.",
    benefits: "Trains protraction of the scapula and eye–hand coordination.",
    gamified: true },
  { slug: "shoulder", name: "Shoulder Circles", category: "pt", track: "arm", icon: "🌀",
    focus: "Shoulder mobility",
    description: "Slow forward and backward shoulder rotations.",
    benefits: "Reduces stiffness and prevents contractures.",
    gamified: true },
  { slug: "leg", name: "Leg Kick", category: "pt", track: "leg", icon: "⭐",
    focus: "Hip flexion",
    description: "Kick the highlighted star with the correct leg.",
    benefits: "Strengthens hip flexors and improves stepping pattern.",
    gamified: true },
  { slug: "march", name: "High March", category: "pt", track: "leg", icon: "🥁",
    focus: "Reciprocal stepping",
    description: "March in place lifting knees to hip height.",
    benefits: "Builds cadence, balance and reciprocal hip control.",
    gamified: true },
  { slug: "squat", name: "Mini Squat", category: "pt", track: "leg", icon: "🏋️",
    focus: "Quadriceps / glutes",
    description: "Bend knees a quarter-way and stand back up.",
    benefits: "Strengthens legs for sit-to-stand and walking.",
    gamified: true },
  { slug: "sitstand", name: "Sit-to-Stand", category: "pt", track: "leg", icon: "🪑",
    focus: "Transfer skill",
    description: "Rise from a chair without using hands, then sit slowly.",
    benefits: "Core, hip and knee extensor strength for daily transfers.",
    gamified: true },
  { slug: "bridge", name: "Bridge", category: "pt", track: "leg", icon: "🌉",
    focus: "Gluteal activation",
    description: "Lying on back, lift hips to form a bridge.",
    benefits: "Activates glutes and lumbar stabilisers.",
    gamified: true },
  { slug: "ankle", name: "Ankle Dorsiflexion", category: "pt", track: "leg", icon: "🦶",
    focus: "Tibialis anterior",
    description: "Point toes up toward shins, hold, release.",
    benefits: "Counters equinus posture and foot-drop.",
    gamified: true },
  { slug: "balance", name: "Balance Hold", category: "pt", track: "balance", icon: "💎",
    focus: "Static balance",
    description: "Stand centered and steady on both feet.",
    benefits: "Postural control needed for all upright activities.",
    gamified: true },
  { slug: "gait", name: "Gait Practice", category: "pt", track: "leg", icon: "🚶",
    focus: "Walking pattern",
    description: "Guided walking with knee flexion cues.",
    benefits: "Improves swing phase and stride symmetry.",
    gamified: true },
  { slug: "trunk", name: "Trunk Rotation", category: "pt", track: "arm", icon: "🌪️",
    focus: "Core mobility",
    description: "Rotate upper body side to side while seated.",
    benefits: "Improves trunk control and midline crossing.",
    gamified: true },
  { slug: "head", name: "Head Control", category: "pt", track: "balance", icon: "👀",
    focus: "Cervical stability",
    description: "Track a moving object with eyes and head.",
    benefits: "Neck strength — foundational for sitting and feeding.",
    gamified: true },
  { slug: "stretch", name: "Hamstring Stretch", category: "pt", track: "balance", icon: "🧘",
    focus: "Flexibility",
    description: "Long-sitting reach toward the toes.",
    benefits: "Reduces hamstring tightness that limits gait.",
    gamified: true },
  { slug: "crawl", name: "Four-Point Crawl", category: "pt", track: "leg", icon: "🐾",
    focus: "Cross-pattern coordination",
    description: "Crawl forward on hands and knees.",
    benefits: "Shoulder girdle, hip stability and bilateral integration.",
    gamified: true },

  // ============ EXPANDED PT — clinically standard for CP, now playable ============
  { slug: "prone", name: "Prone on Elbows", category: "pt", track: "balance", icon: "🛌",
    focus: "Upper-body extension",
    description: "Lie on tummy, prop on forearms, lift head.",
    benefits: "Strengthens neck extensors and shoulder girdle.",
    gamified: true },
  { slug: "sidelying", name: "Side-Lying Play", category: "pt", track: "arm", icon: "↔️",
    focus: "Postural variety",
    description: "Play with both hands while side-lying.",
    benefits: "Encourages midline hand use and reduces asymmetry.",
    gamified: true },
  { slug: "rolling", name: "Rolling Practice", category: "pt", track: "balance", icon: "🔄",
    focus: "Segmental rolling",
    description: "Roll from back to tummy and back again.",
    benefits: "Trunk dissociation, an early motor milestone.",
    gamified: true },
  { slug: "kneeling", name: "Tall Kneeling", category: "pt", track: "balance", icon: "🧎",
    focus: "Hip extension",
    description: "Kneel upright, hips over knees, hold.",
    benefits: "Glute and core control preparing for standing.",
    gamified: true },
  { slug: "half-kneel", name: "Half-Kneeling", category: "pt", track: "balance", icon: "🦵",
    focus: "Unilateral stance prep",
    description: "One knee down, other foot flat, alternate legs.",
    benefits: "Improves single-leg loading and pelvic stability.",
    gamified: true },
  { slug: "wall-stand", name: "Wall-Supported Standing", category: "pt", track: "balance", icon: "🧱",
    focus: "Weight bearing",
    description: "Stand with back and heels to a wall.",
    benefits: "Loads bones and stretches calves.",
    gamified: true },
  { slug: "heel-raise", name: "Heel Raises", category: "pt", track: "leg", icon: "👠",
    focus: "Calf strength",
    description: "Rise onto tiptoes, lower slowly.",
    benefits: "Push-off power for walking.",
    gamified: true },
  { slug: "step-up", name: "Step-Ups", category: "pt", track: "leg", icon: "🪜",
    focus: "Stair skill",
    description: "Step up onto a low block, alternate legs.",
    benefits: "Functional strength for stairs and curbs.",
    gamified: true },
  { slug: "obstacle", name: "Obstacle Stepping", category: "pt", track: "leg", icon: "🚧",
    focus: "Motor planning",
    description: "Step over small objects in a line.",
    benefits: "Foot clearance and dynamic balance.",
    gamified: true },
  { slug: "ball-throw", name: "Therapy-Ball Sit", category: "pt", track: "balance", icon: "🏐",
    focus: "Dynamic sitting",
    description: "Sit on a therapy ball while playing catch.",
    benefits: "Reactive balance and core co-activation.",
    gamified: true },
  { slug: "pnf", name: "PNF Diagonals", category: "pt", track: "arm", icon: "➡️",
    focus: "Neuromuscular facilitation",
    description: "Diagonal arm patterns across the body.",
    benefits: "Facilitates functional multi-joint movement.",
    gamified: true },
  { slug: "aquatic", name: "Aquatic Movement", category: "pt", track: "leg", icon: "🏊",
    focus: "Low-load practice",
    description: "Walking / kicking in shallow water.",
    benefits: "Reduces spasticity, allows freer movement.",
    gamified: true },
  { slug: "horse", name: "Hippotherapy Prep", category: "pt", track: "balance", icon: "🐴",
    focus: "Rhythmic input",
    description: "Sit-astride play on a bolster or peanut ball.",
    benefits: "Simulates hippotherapy for trunk control.",
    gamified: true },
  { slug: "breathing", name: "Diaphragmatic Breathing", category: "pt", track: "balance", icon: "🌬️",
    focus: "Respiratory strength",
    description: "Slow belly breathing, hand on tummy.",
    benefits: "Supports voice, feeding and endurance.",
    gamified: true },

  // ============ OCCUPATIONAL THERAPY (MVP + expanded) ============
  { slug: "pinch", name: "Pinch & Pick", category: "ot", track: "arm", icon: "🤏",
    focus: "Pincer grasp",
    description: "Pick up small objects between thumb and finger.",
    benefits: "Fine motor precision for feeding and writing.",
    gamified: true },
  { slug: "catch", name: "Catch & Toss", category: "ot", track: "arm", icon: "🧤",
    focus: "Hand-eye coordination",
    description: "Catch a soft ball with both hands.",
    benefits: "Bilateral timing and visual tracking.",
    gamified: true },
  { slug: "clap", name: "Rhythm Clap", category: "ot", track: "arm", icon: "👏",
    focus: "Bilateral timing",
    description: "Copy a clapping rhythm.",
    benefits: "Auditory processing and midline coordination.",
    gamified: true },
  { slug: "grip", name: "Grip Strength", category: "ot", track: "arm", icon: "✊",
    focus: "Power grip",
    description: "Squeeze a soft ball, hold, release.",
    benefits: "Hand strength for holding utensils.",
    gamified: true },
  { slug: "midline", name: "Cross the Midline", category: "ot", track: "arm", icon: "🔀",
    focus: "Bilateral integration",
    description: "Touch opposite shoulders and knees.",
    benefits: "Encourages both brain hemispheres to communicate.",
    gamified: true },
  { slug: "draw", name: "Big Drawing", category: "ot", track: "arm", icon: "✏️",
    focus: "Pre-writing",
    description: "Draw large shapes in the air or on paper.",
    benefits: "Shoulder stability that underpins handwriting.",
    gamified: true },
  { slug: "dress", name: "Dressing Skills", category: "ot", track: "arm", icon: "🧥",
    focus: "Self-care ADL",
    description: "Practice putting arms into a shirt.",
    benefits: "Independence in daily dressing.",
    gamified: true },
  { slug: "feed", name: "Spoon Feeding", category: "ot", track: "arm", icon: "🥄",
    focus: "Self-feeding",
    description: "Scoop and bring spoon to mouth.",
    benefits: "Coordinated arm–mouth motion for meals.",
    gamified: true },
  { slug: "track", name: "Visual Tracking", category: "ot", track: "balance", icon: "🎯",
    focus: "Ocular motor",
    description: "Follow a moving target with eyes only.",
    benefits: "Reading and environmental scanning.",
    gamified: true },
  { slug: "simon", name: "Simon Says", category: "ot", track: "arm", icon: "🧠",
    focus: "Cognition + motor",
    description: "Copy multi-step actions on command.",
    benefits: "Working memory and motor planning.",
    gamified: true },
  { slug: "sensory", name: "Sensory Exploration", category: "ot", track: "arm", icon: "🌈",
    focus: "Tactile input",
    description: "Explore different textures with hands.",
    benefits: "Sensory processing and body awareness.",
    gamified: true },
  { slug: "bilateral", name: "Two-Hand Play", category: "ot", track: "arm", icon: "🤝",
    focus: "Bilateral hand use",
    description: "Hold container with one hand, drop items with the other.",
    benefits: "Coordinated dominant / assistive hand roles.",
    gamified: true },

  // ============ EXPANDED OT — now playable ============
  { slug: "beads", name: "Threading Beads", category: "ot", track: "arm", icon: "📿",
    focus: "In-hand manipulation",
    description: "Thread large beads onto a string.",
    benefits: "Finger dexterity and visual planning.",
    gamified: true },
  { slug: "buttons", name: "Buttoning", category: "ot", track: "arm", icon: "🔘",
    focus: "Fasteners ADL",
    description: "Fasten and unfasten large buttons.",
    benefits: "Independence with clothing.",
    gamified: true },
  { slug: "cut", name: "Scissor Skills", category: "ot", track: "arm", icon: "✂️",
    focus: "Bilateral cutting",
    description: "Cut along a thick line with safety scissors.",
    benefits: "Hand separation and school readiness.",
    gamified: true },
  { slug: "puzzle", name: "Puzzles & Shape-Sort", category: "ot", track: "arm", icon: "🧩",
    focus: "Visual-spatial",
    description: "Match shapes into a sorter.",
    benefits: "Perception, rotation and problem-solving.",
    gamified: true },
  { slug: "playdough", name: "Play-Dough Work", category: "ot", track: "arm", icon: "🟠",
    focus: "Hand strength",
    description: "Roll, pinch and shape dough.",
    benefits: "Arch development in the hand.",
    gamified: true },
  { slug: "oral", name: "Oral-Motor Play", category: "ot", track: "arm", icon: "👄",
    focus: "Feeding / speech prep",
    description: "Straw drinking, blowing bubbles.",
    benefits: "Lip closure and tongue control.",
    gamified: true },
  { slug: "brush", name: "Sensory Brushing", category: "ot", track: "arm", icon: "🪥",
    focus: "Tactile regulation",
    description: "Firm brushing of limbs (per OT plan).",
    benefits: "Reduces tactile defensiveness.",
    gamified: true },
  { slug: "handwriting", name: "Pre-Writing Strokes", category: "ot", track: "arm", icon: "📝",
    focus: "Handwriting readiness",
    description: "Trace lines, circles and crosses.",
    benefits: "Foundational strokes for letters.",
    gamified: true },
  { slug: "toilet", name: "Toileting Steps", category: "ot", track: "arm", icon: "🚻",
    focus: "Self-care routine",
    description: "Practice sequence: pull down, sit, wipe, wash.",
    benefits: "Independence and dignity in daily routine.",
    gamified: true },
];

export const CATEGORY_LABEL: Record<ExerciseCategory, string> = {
  pt: "Physiotherapy",
  ot: "Occupational therapy",
};
