// Full exercise catalog for CP therapy — 29 Physiotherapy + 21 Occupational Therapy (50 exercises total).
// The `slug` maps to the id used in public/neuro-bridge/app.js so the in-app
// launcher can pre-select the same exercise inside the prototype player.

export type ExerciseCategory = "pt" | "ot";
export type ExerciseTrack = "arm" | "leg" | "balance";

export type Exercise = {
  slug: string;
  name: string;
  category: ExerciseCategory;
  track: ExerciseTrack;
  icon: string;
  focus: string;
  description: string;
  benefits: string;
  gamified: boolean;
};

export const EXERCISES: Exercise[] = [
  // ============ PHYSIOTHERAPY (29) ============
  {
    slug: "arm",
    name: "\n",
    category: "pt",
    track: "arm",
    icon: "\n",
    focus: "\n",
    description: "Raise arms overhead slowly to target height.",
    benefits: "Improves shoulder ROM, upper-limb strength and posture.",
    gamified: true,
  },
  {
    slug: "reach",
    name: "Bend and straighten",
    category: "pt",
    track: "arm",
    icon: "\n",
    focus: "Flexion and extension",
    description: "Reach forward to touch an on-screen target.",
    benefits: "Trains protraction of the scapula and eye–hand coordination.",
    gamified: true,
  },
  {
    slug: "shoulder",
    name: "Palm up, palm down",
    category: "pt",
    track: "arm",
    icon: "\n",
    focus: "Forearm rotation, supination and pronation",
    description: "Slow forward and backward shoulder rotations.",
    benefits: "Reduces stiffness and prevents contractures.",
    gamified: true,
  },
  {
    slug: "leg",
    name: "Leg Kick",
    category: "pt",
    track: "leg",
    icon: "⭐",
    focus: "Hip flexion",
    description: "Kick toward the highlighted target with the active leg.",
    benefits: "Strengthens hip flexors and improves stepping pattern.",
    gamified: true,
  },
  {
    slug: "march",
    name: "High March",
    category: "pt",
    track: "leg",
    icon: "🥁",
    focus: "Reciprocal stepping",
    description: "March in place lifting knees to hip height.",
    benefits: "Builds cadence, balance and reciprocal hip control.",
    gamified: true,
  },
  {
    slug: "squat",
    name: "Mini Squat",
    category: "pt",
    track: "leg",
    icon: "🏋️",
    focus: "Quadriceps / glutes",
    description: "Bend knees a quarter-way and stand back up.",
    benefits: "Strengthens legs for sit-to-stand and walking.",
    gamified: true,
  },
  {
    slug: "ankle",
    name: "Ankle Pumps",
    category: "pt",
    track: "leg",
    icon: "🦶",
    focus: "Ankle mobility",
    description: "Point toes forward, pull back towards shins.",
    benefits: "Maintains ankle range, counters foot-drop, and supports circulation.",
    gamified: true,
  },
  {
    slug: "wall-pushup",
    name: "Wall Push-Up",
    category: "pt",
    track: "arm",
    icon: "🧱",
    focus: "Upper-body pushing",
    description: "Push off from a smooth wall using both arms.",
    benefits: "Builds upper body strength with joint-friendly weight bearing.",
    gamified: true,
  },
  {
    slug: "side-bend",
    name: "Side Bend",
    category: "pt",
    track: "arm",
    icon: "↔️",
    focus: "Trunk mobility",
    description: "Gently lean torso side to side while seated or standing.",
    benefits: "Improves lateral trunk control and core activation.",
    gamified: true,
  },
  {
    slug: "heel-toe",
    name: "Heel-to-Toe Walk",
    category: "pt",
    track: "leg",
    icon: "👣",
    focus: "Dynamic balance",
    description: "Walk in a line placing heel directly in front of toe.",
    benefits: "Trains balance and controlled foot placement.",
    gamified: true,
  },
  {
    slug: "balance",
    name: "Standing Balance",
    category: "pt",
    track: "balance",
    icon: "💎",
    focus: "Static balance",
    description: "Stand centered and steady on both feet.",
    benefits: "Builds postural control and standing endurance.",
    gamified: true,
  },
  {
    slug: "trunk",
    name: "Seated Trunk Rotation",
    category: "pt",
    track: "arm",
    icon: "🌪️",
    focus: "Core rotation",
    description: "Rotate upper body side to side while seated.",
    benefits: "Improves trunk rotation used in reaching and dressing.",
    gamified: true,
  },
  {
    slug: "hip-abduction",
    name: "Hip Abduction",
    category: "pt",
    track: "leg",
    icon: "🦵",
    focus: "Hip strength",
    description: "Lift leg sideways away from midline.",
    benefits: "Strengthens hip stabilizers for walking and standing.",
    gamified: true,
  },
  {
    slug: "bridge",
    name: "Bridge Lift",
    category: "pt",
    track: "leg",
    icon: "🌉",
    focus: "Glute / core",
    description: "Lying on back with knees bent, lift hips into a bridge.",
    benefits: "Builds core and pelvic stability.",
    gamified: true,
  },
  {
    slug: "step-up",
    name: "Step-Up",
    category: "pt",
    track: "leg",
    icon: "🪜",
    focus: "Functional strength",
    description: "Step up onto a low block, alternate legs.",
    benefits: "Trains stair and curb navigation strength.",
    gamified: true,
  },
  {
    slug: "toe-taps",
    name: "Toe Taps",
    category: "pt",
    track: "leg",
    icon: "🎶",
    focus: "Foot control",
    description: "Tap toes repeatedly while keeping heel flat.",
    benefits: "Improves selective foot and ankle movement.",
    gamified: true,
  },
  {
    slug: "knee-extension",
    name: "Knee Extension",
    category: "pt",
    track: "leg",
    icon: "🦵",
    focus: "Quadriceps",
    description: "Straighten knee from seated position, hold, lower.",
    benefits: "Strengthens knee extensors for standing stability.",
    gamified: true,
  },
  {
    slug: "heel-raise",
    name: "Calf Raise",
    category: "pt",
    track: "leg",
    icon: "👠",
    focus: "Lower-leg strength",
    description: "Rise onto tiptoes slowly and control lower.",
    benefits: "Builds push-off strength for walking.",
    gamified: true,
  },
  {
    slug: "pelvic-tilt",
    name: "Pelvic Tilt",
    category: "pt",
    track: "balance",
    icon: "🔄",
    focus: "Core control",
    description: "Flatten lower back into mat/chair then gently arch.",
    benefits: "Improves pelvic control and lumbar awareness.",
    gamified: true,
  },
  {
    slug: "arm-circles",
    name: "Arm lowering",
    category: "pt",
    track: "arm",
    icon: "\n",
    focus: "Shoulder Extension",
    description: "Make small then medium circles with outstretched arms.",
    benefits: "Builds shoulder endurance and movement control.",
    gamified: true,
  },
  {
    slug: "lunge-reach",
    name: "Lunge Reach",
    category: "pt",
    track: "leg",
    icon: "🏹",
    focus: "Balance + reach",
    description: "Step forward into mini-lunge and reach with opposite hand.",
    benefits: "Combines dynamic balance with a functional reaching pattern.",
    gamified: true,
  },
  {
    slug: "star-jump",
    name: "Star Jump (Modified)",
    category: "pt",
    track: "arm",
    icon: "✨",
    focus: "Coordination",
    description: "Step side-to-side while raising arms in star pattern.",
    benefits: "Full-body coordination at a gentle, adapted pace.",
    gamified: true,
  },
  {
    slug: "crawl",
    name: "Crawl Pattern",
    category: "pt",
    track: "leg",
    icon: "🐾",
    focus: "Cross-body coordination",
    description: "Move opposite arm and knee forward on hands and knees.",
    benefits: "Reinforces reciprocal cross-body movement.",
    gamified: true,
  },
  {
    slug: "sitstand",
    name: "Sit-to-Stand",
    category: "pt",
    track: "leg",
    icon: "🪑",
    focus: "Functional transfer",
    description: "Rise from a chair with control, then sit back slowly.",
    benefits: "Trains the most-used daily transfer movement.",
    gamified: true,
  },
  {
    slug: "wall-slide",
    name: "Rotation",
    category: "pt",
    track: "arm",
    icon: "\n",
    focus: "Internal and external rotation",
    description: "Slide arms up a wall while keeping forearms flat.",
    benefits: "Improves shoulder mechanics and upright posture.",
    gamified: true,
  },
  {
    slug: "single-leg",
    name: "Single-Leg Stand",
    category: "pt",
    track: "balance",
    icon: "🦩",
    focus: "Single-limb balance",
    description: "Balance on one leg with light support nearby.",
    benefits: "Builds single-limb balance and stride confidence.",
    gamified: true,
  },
  {
    slug: "backward-walk",
    name: "Backward Walk",
    category: "pt",
    track: "leg",
    icon: "🔙",
    focus: "Gait variation",
    description: "Walk backward slowly in a safe, open space.",
    benefits: "Improves proprioception and gait adaptability.",
    gamified: true,
  },
  {
    slug: "obstacle",
    name: "Obstacle Step",
    category: "pt",
    track: "leg",
    icon: "🚧",
    focus: "Functional mobility",
    description: "Step over small soft objects placed in a line.",
    benefits: "Practices safe stepping over daily obstacles.",
    gamified: true,
  },
  {
    slug: "band-pull",
    name: "Resistance Band Pull",
    category: "pt",
    track: "arm",
    icon: "🎗️",
    focus: "Upper-body strength",
    description: "Pull band horizontally across chest.",
    benefits: "Builds pulling strength for daily independence tasks.",
    gamified: true,
  },

  // ============ OCCUPATIONAL THERAPY (21) ============
  {
    slug: "pinch",
    name: "Pinch & Pick",
    category: "ot",
    track: "arm",
    icon: "🤏",
    focus: "Pincer grasp",
    description: "Pinch small items between index finger and thumb.",
    benefits: "Fine motor precision for feeding and writing.",
    gamified: true,
  },
  {
    slug: "catch",
    name: "Catch & Toss",
    category: "ot",
    track: "arm",
    icon: "🧤",
    focus: "Hand-eye coordination",
    description: "Catch and toss a soft ball with both hands.",
    benefits: "Bilateral timing and visual tracking.",
    gamified: true,
  },
  {
    slug: "clap",
    name: "Rhythm Clap",
    category: "ot",
    track: "arm",
    icon: "👏",
    focus: "Bilateral timing",
    description: "Clap in time to rhythmic audio or visual prompts.",
    benefits: "Auditory processing and midline coordination.",
    gamified: true,
  },
  {
    slug: "grip",
    name: "Grip Strength",
    category: "ot",
    track: "arm",
    icon: "✊",
    focus: "Power grip",
    description: "Squeeze a soft sponge or therapy ball.",
    benefits: "Hand strength for holding utensils and cups.",
    gamified: true,
  },
  {
    slug: "midline",
    name: "Cross the Midline",
    category: "ot",
    track: "arm",
    icon: "\n",
    focus: "Adduction",
    description: "Touch hand to opposite shoulder, hip, and knee.",
    benefits: "Encourages both brain hemispheres to communicate.",
    gamified: true,
  },
  {
    slug: "draw",
    name: "Big Drawing",
    category: "ot",
    track: "arm",
    icon: "✏️",
    focus: "Pre-writing",
    description: "Draw sweeping circles and lines in the air.",
    benefits: "Shoulder stability that underpins handwriting.",
    gamified: true,
  },
  {
    slug: "buttons",
    name: "Button Practice",
    category: "ot",
    track: "arm",
    icon: "🔘",
    focus: "Fine motor / dressing",
    description: "Practice pushing large buttons through buttonholes.",
    benefits: "Builds independence with self-dressing tasks.",
    gamified: true,
  },
  {
    slug: "zipper",
    name: "Zipper Pull",
    category: "ot",
    track: "arm",
    icon: "🤐",
    focus: "Fine motor / dressing",
    description: "Grasp zipper tab and pull smoothly.",
    benefits: "Trains grip and pull coordination for dressing.",
    gamified: true,
  },
  {
    slug: "puzzle",
    name: "Puzzle Match",
    category: "ot",
    track: "arm",
    icon: "🧩",
    focus: "Visual-motor integration",
    description: "Grasp puzzle pieces and rotate into slots.",
    benefits: "Links visual perception to hand placement.",
    gamified: true,
  },
  {
    slug: "beads",
    name: "Bead Threading",
    category: "ot",
    track: "arm",
    icon: "📿",
    focus: "Fine motor precision",
    description: "Thread large beads onto a thick string.",
    benefits: "Builds precision grasp and hand stability.",
    gamified: true,
  },
  {
    slug: "cut",
    name: "Scissor Snips",
    category: "ot",
    track: "arm",
    icon: "✂️",
    focus: "Bilateral hand use",
    description: "Make small snips along card edges with safety scissors.",
    benefits: "Trains coordinated two-hand cutting control.",
    gamified: true,
  },
  {
    slug: "playdough",
    name: "Playdough Squeeze",
    category: "ot",
    track: "arm",
    icon: "🟠",
    focus: "Hand strength",
    description: "Roll, pinch, and flatten dough with hands.",
    benefits: "Builds intrinsic hand muscle strength.",
    gamified: true,
  },
  {
    slug: "stacking",
    name: "Stacking Blocks",
    category: "ot",
    track: "arm",
    icon: "🧱",
    focus: "Visual-motor control",
    description: "Stack blocks smoothly into a high tower.",
    benefits: "Trains grading of movement and placement accuracy.",
    gamified: true,
  },
  {
    slug: "spoon",
    name: "Spoon Scoop",
    category: "ot",
    track: "arm",
    icon: "🥄",
    focus: "Self-feeding skill",
    description: "Scoop beads with a spoon and carry to a bowl.",
    benefits: "Builds wrist control for independent feeding.",
    gamified: true,
  },
  {
    slug: "page-turn",
    name: "Page Turn",
    category: "ot",
    track: "arm",
    icon: "📖",
    focus: "Fine motor isolation",
    description: "Turn pages of a board book one by one.",
    benefits: "Trains isolated finger movement and thumb opposition.",
    gamified: true,
  },
  {
    slug: "pegboard",
    name: "Peg Board",
    category: "ot",
    track: "arm",
    icon: "📍",
    focus: "Precision grasp",
    description: "Pick up pegs and place into board holes.",
    benefits: "Builds pincer precision and hand-eye timing.",
    gamified: true,
  },
  {
    slug: "tracing",
    name: "Tracing Lines",
    category: "ot",
    track: "arm",
    icon: "📝",
    focus: "Pre-writing control",
    description: "Trace straight and curved lines on paper or screen.",
    benefits: "Prepares hand control for letter formation.",
    gamified: true,
  },
  {
    slug: "shapes",
    name: "Sorting Shapes",
    category: "ot",
    track: "arm",
    icon: "🔷",
    focus: "Visual discrimination",
    description: "Sort objects into matching color and shape bins.",
    benefits: "Links visual sorting with motor placement.",
    gamified: true,
  },
  {
    slug: "carry",
    name: "Two-Hand Carry",
    category: "ot",
    track: "arm",
    icon: "📦",
    focus: "Bilateral coordination",
    description: "Hold a tray or box with both hands while walking.",
    benefits: "Trains carrying with both hands together.",
    gamified: true,
  },
  {
    slug: "finger-tap",
    name: "Finger Tap Sequence",
    category: "ot",
    track: "arm",
    icon: "🎹",
    focus: "Fine motor sequencing",
    description: "Tap each finger to thumb in order.",
    benefits: "Builds finger isolation and sequencing.",
    gamified: true,
  },
  {
    slug: "ball-roll",
    name: "Bilateral Ball Roll",
    category: "ot",
    track: "arm",
    icon: "⚽",
    focus: "Bilateral coordination",
    description: "Roll a large ball forward using both palms.",
    benefits: "Trains symmetric two-hand control.",
    gamified: true,
  },
];

export const CATEGORY_LABEL: Record<ExerciseCategory, string> = {
  pt: "Physiotherapy",
  ot: "Occupational therapy",
};
