/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppCaregiverRouteImport } from './routes/_authenticated/app.caregiver'
import { Route as AuthenticatedAppExercisesRouteImport } from './routes/_authenticated/app.exercises'
import { Route as AuthenticatedAppProgressRouteImport } from './routes/_authenticated/app.progress'
import { Route as AuthenticatedAppTherapistRouteImport } from './routes/_authenticated/app.therapist'
import { Route as AuthenticatedAppTrainingRouteImport } from './routes/_authenticated/app.training'
import { Route as AuthenticatedAppTherapistIndexRouteImport } from './routes/_authenticated/app.therapist.index'
import { Route as AuthenticatedAppTherapistProfileRouteImport } from './routes/_authenticated/app.therapist.profile'
import { Route as AuthenticatedAppTherapistRequestsRouteImport } from './routes/_authenticated/app.therapist.requests'
import { Route as AuthenticatedAppTherapistVisitsRouteImport } from './routes/_authenticated/app.therapist.visits'
import { Route as AuthenticatedAppTherapistPatientPatientIdRouteImport } from './routes/_authenticated/app.therapist.patient.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCaregiverRoute =
  AuthenticatedAppCaregiverRouteImport.update({
    id: '/caregiver',
    path: '/caregiver',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExercisesRoute =
  AuthenticatedAppExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProgressRoute =
  AuthenticatedAppProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTherapistRoute =
  AuthenticatedAppTherapistRouteImport.update({
    id: '/therapist',
    path: '/therapist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrainingRoute =
  AuthenticatedAppTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTherapistIndexRoute =
  AuthenticatedAppTherapistIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppTherapistRoute,
  } as any)
const AuthenticatedAppTherapistProfileRoute =
  AuthenticatedAppTherapistProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAppTherapistRoute,
  } as any)
const AuthenticatedAppTherapistRequestsRoute =
  AuthenticatedAppTherapistRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppTherapistRoute,
  } as any)
const AuthenticatedAppTherapistVisitsRoute =
  AuthenticatedAppTherapistVisitsRouteImport.update({
    id: '/visits',
    path: '/visits',
    getParentRoute: () => AuthenticatedAppTherapistRoute,
  } as any)
const AuthenticatedAppTherapistPatientPatientIdRoute =
  AuthenticatedAppTherapistPatientPatientIdRouteImport.update({
    id: '/patient/$patientId',
    path: '/patient/$patientId',
    getParentRoute: () => AuthenticatedAppTherapistRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/caregiver': typeof AuthenticatedAppCaregiverRoute
  '/app/exercises': typeof AuthenticatedAppExercisesRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/therapist': typeof AuthenticatedAppTherapistRouteWithChildren
  '/app/training': typeof AuthenticatedAppTrainingRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/therapist/profile': typeof AuthenticatedAppTherapistProfileRoute
  '/app/therapist/requests': typeof AuthenticatedAppTherapistRequestsRoute
  '/app/therapist/visits': typeof AuthenticatedAppTherapistVisitsRoute
  '/app/therapist/': typeof AuthenticatedAppTherapistIndexRoute
  '/app/therapist/patient/$patientId': typeof AuthenticatedAppTherapistPatientPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/caregiver': typeof AuthenticatedAppCaregiverRoute
  '/app/exercises': typeof AuthenticatedAppExercisesRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/training': typeof AuthenticatedAppTrainingRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/therapist/profile': typeof AuthenticatedAppTherapistProfileRoute
  '/app/therapist/requests': typeof AuthenticatedAppTherapistRequestsRoute
  '/app/therapist/visits': typeof AuthenticatedAppTherapistVisitsRoute
  '/app/therapist': typeof AuthenticatedAppTherapistIndexRoute
  '/app/therapist/patient/$patientId': typeof AuthenticatedAppTherapistPatientPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/caregiver': typeof AuthenticatedAppCaregiverRoute
  '/_authenticated/app/exercises': typeof AuthenticatedAppExercisesRoute
  '/_authenticated/app/progress': typeof AuthenticatedAppProgressRoute
  '/_authenticated/app/therapist': typeof AuthenticatedAppTherapistRouteWithChildren
  '/_authenticated/app/training': typeof AuthenticatedAppTrainingRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/therapist/profile': typeof AuthenticatedAppTherapistProfileRoute
  '/_authenticated/app/therapist/requests': typeof AuthenticatedAppTherapistRequestsRoute
  '/_authenticated/app/therapist/visits': typeof AuthenticatedAppTherapistVisitsRoute
  '/_authenticated/app/therapist/': typeof AuthenticatedAppTherapistIndexRoute
  '/_authenticated/app/therapist/patient/$patientId': typeof AuthenticatedAppTherapistPatientPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/admin'
    | '/app/caregiver'
    | '/app/exercises'
    | '/app/progress'
    | '/app/therapist'
    | '/app/training'
    | '/app/'
    | '/app/therapist/profile'
    | '/app/therapist/requests'
    | '/app/therapist/visits'
    | '/app/therapist/'
    | '/app/therapist/patient/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/admin'
    | '/app/caregiver'
    | '/app/exercises'
    | '/app/progress'
    | '/app/training'
    | '/app'
    | '/app/therapist/profile'
    | '/app/therapist/requests'
    | '/app/therapist/visits'
    | '/app/therapist'
    | '/app/therapist/patient/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/caregiver'
    | '/_authenticated/app/exercises'
    | '/_authenticated/app/progress'
    | '/_authenticated/app/therapist'
    | '/_authenticated/app/training'
    | '/_authenticated/app/'
    | '/_authenticated/app/therapist/profile'
    | '/_authenticated/app/therapist/requests'
    | '/_authenticated/app/therapist/visits'
    | '/_authenticated/app/therapist/'
    | '/_authenticated/app/therapist/patient/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/caregiver': {
      id: '/_authenticated/app/caregiver'
      path: '/caregiver'
      fullPath: '/app/caregiver'
      preLoaderRoute: typeof AuthenticatedAppCaregiverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/exercises': {
      id: '/_authenticated/app/exercises'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AuthenticatedAppExercisesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progress': {
      id: '/_authenticated/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AuthenticatedAppProgressRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/therapist': {
      id: '/_authenticated/app/therapist'
      path: '/therapist'
      fullPath: '/app/therapist'
      preLoaderRoute: typeof AuthenticatedAppTherapistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/training': {
      id: '/_authenticated/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AuthenticatedAppTrainingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/therapist/': {
      id: '/_authenticated/app/therapist/'
      path: '/'
      fullPath: '/app/therapist/'
      preLoaderRoute: typeof AuthenticatedAppTherapistIndexRouteImport
      parentRoute: typeof AuthenticatedAppTherapistRoute
    }
    '/_authenticated/app/therapist/profile': {
      id: '/_authenticated/app/therapist/profile'
      path: '/profile'
      fullPath: '/app/therapist/profile'
      preLoaderRoute: typeof AuthenticatedAppTherapistProfileRouteImport
      parentRoute: typeof AuthenticatedAppTherapistRoute
    }
    '/_authenticated/app/therapist/requests': {
      id: '/_authenticated/app/therapist/requests'
      path: '/requests'
      fullPath: '/app/therapist/requests'
      preLoaderRoute: typeof AuthenticatedAppTherapistRequestsRouteImport
      parentRoute: typeof AuthenticatedAppTherapistRoute
    }
    '/_authenticated/app/therapist/visits': {
      id: '/_authenticated/app/therapist/visits'
      path: '/visits'
      fullPath: '/app/therapist/visits'
      preLoaderRoute: typeof AuthenticatedAppTherapistVisitsRouteImport
      parentRoute: typeof AuthenticatedAppTherapistRoute
    }
    '/_authenticated/app/therapist/patient/$patientId': {
      id: '/_authenticated/app/therapist/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/app/therapist/patient/$patientId'
      preLoaderRoute: typeof AuthenticatedAppTherapistPatientPatientIdRouteImport
      parentRoute: typeof AuthenticatedAppTherapistRoute
    }
  }
}

interface AuthenticatedAppTherapistRouteChildren {
  AuthenticatedAppTherapistProfileRoute: typeof AuthenticatedAppTherapistProfileRoute
  AuthenticatedAppTherapistRequestsRoute: typeof AuthenticatedAppTherapistRequestsRoute
  AuthenticatedAppTherapistVisitsRoute: typeof AuthenticatedAppTherapistVisitsRoute
  AuthenticatedAppTherapistIndexRoute: typeof AuthenticatedAppTherapistIndexRoute
  AuthenticatedAppTherapistPatientPatientIdRoute: typeof AuthenticatedAppTherapistPatientPatientIdRoute
}

const AuthenticatedAppTherapistRouteChildren: AuthenticatedAppTherapistRouteChildren =
  {
    AuthenticatedAppTherapistProfileRoute:
      AuthenticatedAppTherapistProfileRoute,
    AuthenticatedAppTherapistRequestsRoute:
      AuthenticatedAppTherapistRequestsRoute,
    AuthenticatedAppTherapistVisitsRoute: AuthenticatedAppTherapistVisitsRoute,
    AuthenticatedAppTherapistIndexRoute: AuthenticatedAppTherapistIndexRoute,
    AuthenticatedAppTherapistPatientPatientIdRoute:
      AuthenticatedAppTherapistPatientPatientIdRoute,
  }

const AuthenticatedAppTherapistRouteWithChildren =
  AuthenticatedAppTherapistRoute._addFileChildren(
    AuthenticatedAppTherapistRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppCaregiverRoute: typeof AuthenticatedAppCaregiverRoute
  AuthenticatedAppExercisesRoute: typeof AuthenticatedAppExercisesRoute
  AuthenticatedAppProgressRoute: typeof AuthenticatedAppProgressRoute
  AuthenticatedAppTherapistRoute: typeof AuthenticatedAppTherapistRouteWithChildren
  AuthenticatedAppTrainingRoute: typeof AuthenticatedAppTrainingRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppCaregiverRoute: AuthenticatedAppCaregiverRoute,
  AuthenticatedAppExercisesRoute: AuthenticatedAppExercisesRoute,
  AuthenticatedAppProgressRoute: AuthenticatedAppProgressRoute,
  AuthenticatedAppTherapistRoute: AuthenticatedAppTherapistRouteWithChildren,
  AuthenticatedAppTrainingRoute: AuthenticatedAppTrainingRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
