/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTrainingRouteImport } from './routes/_authenticated/app.training'
import { Route as AuthenticatedAppTherapistRouteImport } from './routes/_authenticated/app.therapist'
import { Route as AuthenticatedAppExercisesRouteImport } from './routes/_authenticated/app.exercises'
import { Route as AuthenticatedAppCaregiverRouteImport } from './routes/_authenticated/app.caregiver'
import { Route as AuthenticatedAppTherapistPatientPatientIdRouteImport } from './routes/_authenticated/app.therapist.patient.$patientId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrainingRoute =
  AuthenticatedAppTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTherapistRoute =
  AuthenticatedAppTherapistRouteImport.update({
    id: '/therapist',
    path: '/therapist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExercisesRoute =
  AuthenticatedAppExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCaregiverRoute =
  AuthenticatedAppCaregiverRouteImport.update({
    id: '/caregiver',
    path: '/caregiver',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTherapistPatientPatientIdRoute =
  AuthenticatedAppTherapistPatientPatientIdRouteImport.update({
    id: '/patient/$patientId',
    path: '/patient/$patientId',
    getParentRoute: () => AuthenticatedAppTherapistRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/caregiver': typeof AuthenticatedAppCaregiverRoute
  '/app/exercises': typeof AuthenticatedAppExercisesRoute
  '/app/therapist': typeof AuthenticatedAppTherapistRouteWithChildren
  '/app/training': typeof AuthenticatedAppTrainingRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/therapist/patient/$patientId': typeof AuthenticatedAppTherapistPatientPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/caregiver': typeof AuthenticatedAppCaregiverRoute
  '/app/exercises': typeof AuthenticatedAppExercisesRoute
  '/app/therapist': typeof AuthenticatedAppTherapistRouteWithChildren
  '/app/training': typeof AuthenticatedAppTrainingRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/therapist/patient/$patientId': typeof AuthenticatedAppTherapistPatientPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/caregiver': typeof AuthenticatedAppCaregiverRoute
  '/_authenticated/app/exercises': typeof AuthenticatedAppExercisesRoute
  '/_authenticated/app/therapist': typeof AuthenticatedAppTherapistRouteWithChildren
  '/_authenticated/app/training': typeof AuthenticatedAppTrainingRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/therapist/patient/$patientId': typeof AuthenticatedAppTherapistPatientPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/caregiver'
    | '/app/exercises'
    | '/app/therapist'
    | '/app/training'
    | '/app/'
    | '/app/therapist/patient/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/caregiver'
    | '/app/exercises'
    | '/app/therapist'
    | '/app/training'
    | '/app'
    | '/app/therapist/patient/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/caregiver'
    | '/_authenticated/app/exercises'
    | '/_authenticated/app/therapist'
    | '/_authenticated/app/training'
    | '/_authenticated/app/'
    | '/_authenticated/app/therapist/patient/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/training': {
      id: '/_authenticated/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AuthenticatedAppTrainingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/therapist': {
      id: '/_authenticated/app/therapist'
      path: '/therapist'
      fullPath: '/app/therapist'
      preLoaderRoute: typeof AuthenticatedAppTherapistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/exercises': {
      id: '/_authenticated/app/exercises'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AuthenticatedAppExercisesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/caregiver': {
      id: '/_authenticated/app/caregiver'
      path: '/caregiver'
      fullPath: '/app/caregiver'
      preLoaderRoute: typeof AuthenticatedAppCaregiverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/therapist/patient/$patientId': {
      id: '/_authenticated/app/therapist/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/app/therapist/patient/$patientId'
      preLoaderRoute: typeof AuthenticatedAppTherapistPatientPatientIdRouteImport
      parentRoute: typeof AuthenticatedAppTherapistRoute
    }
  }
}

interface AuthenticatedAppTherapistRouteChildren {
  AuthenticatedAppTherapistPatientPatientIdRoute: typeof AuthenticatedAppTherapistPatientPatientIdRoute
}

const AuthenticatedAppTherapistRouteChildren: AuthenticatedAppTherapistRouteChildren =
  {
    AuthenticatedAppTherapistPatientPatientIdRoute:
      AuthenticatedAppTherapistPatientPatientIdRoute,
  }

const AuthenticatedAppTherapistRouteWithChildren =
  AuthenticatedAppTherapistRoute._addFileChildren(
    AuthenticatedAppTherapistRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCaregiverRoute: typeof AuthenticatedAppCaregiverRoute
  AuthenticatedAppExercisesRoute: typeof AuthenticatedAppExercisesRoute
  AuthenticatedAppTherapistRoute: typeof AuthenticatedAppTherapistRouteWithChildren
  AuthenticatedAppTrainingRoute: typeof AuthenticatedAppTrainingRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCaregiverRoute: AuthenticatedAppCaregiverRoute,
  AuthenticatedAppExercisesRoute: AuthenticatedAppExercisesRoute,
  AuthenticatedAppTherapistRoute: AuthenticatedAppTherapistRouteWithChildren,
  AuthenticatedAppTrainingRoute: AuthenticatedAppTrainingRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
